fs:
    weight_dir: '/workspace/src/out/weights'
    log_dir: '/workspace/src/out/logs'
wandb: 
    log: True
    project: 'MyProj'
data: 
    prostate:
        pmri:
            data_path: '/data/Data/PMRI/'
            data_key: 'image'
            seg_key: 'label'
unet:
    prostate:
        pmri:
            n_chans_in: 1
            n_chans_out: 2
            training:
                vendor: 'siemens'
                load_only_present: False
                augment: True
                validation: True
                batch_size: 16
                num_batches_per_epoch: 256
                num_val_batches_per_epoch: 32 
                epochs: 100
                patience: 4
                lr: 0.001
